---
- name: create
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_file }}"
    ansible_ssh_user: "{{ ssh_user }}"

  tasks:
    - name: Install consul module for python
      pip:
        name: python-consul

    - name: Inject Push Gateway instance to Radon Consul
      consul:
        service_name: "{{ pushgateway_ip }}_push_gateway"
        service_port: "{{ pushgateway_service_port }}"
        service_address: "{{ pushgateway_ip }}"
        host: "{{ consul_ip }}"
